name: Deploy Hexo Blog

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Node.js
        uses: actions/setup-node@v4
        
      - name: 安装依赖
        run: npm install
        
      - name: 强力修复插件冲突并生成页面
        run: |
          npm uninstall hexo-generator-json-content
          npx hexo clean
          npx hexo generate
        
      - name: 部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: ./public
          publish_branch: gh-pages
          force_orphan: true
